// Generated by CoffeeScript 1.9.3
(function() {
  var CLI, app, auth, basic, config, expandHomeDir, express, model, port, pushover, repos;

  express = require('express');

  pushover = require('pushover');

  expandHomeDir = require('expand-home-dir');

  config = require('./config');

  CLI = require('./CLI');

  config = require('./config');

  model = require('./model');

  auth = require('http-auth');

  basic = auth.basic({
    realm: "GIT deploy-server"
  }, function(username, password, callback) {
    return model.authorizeUser(username, password, function(err, authorized) {
      if (err) {
        return callback(false);
      }
      return callback(authorized);
    });
  });

  app = new express();

  repos = pushover(expandHomeDir(config.REPO_BASE_PATH), {
    autoCreate: false
  });

  app.use(function(req, res, next) {
    return model.getUsers(function(err, users) {
      if (err) {
        return callback(err);
      }
      if (users.length === 0) {
        return next();
      }
      return auth.connect(basic)(req, res, next);
    });
  });

  app.use(function(req, res, next) {
    return repos.handle(req, res);
  });

  port = process.env.PORT || 5000;

  app.listen(port, function(err) {
    if (err) {
      return console.error(port, err);
    }
    return console.log('listening on', port);
  });

}).call(this);
